"""init migration

Revision ID: 246ff8d13f22
Revises: 2f645788654
Create Date: 2017-03-09 18:02:55.845000

"""

# revision identifiers, used by Alembic.
revision = '246ff8d13f22'
down_revision = '2f645788654'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('realvalue', sa.Float(), nullable=True),
    sa.Column('measurevalue', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revises')
    ### end Alembic commands ###
