"""init migration

Revision ID: 398210bf0783
Revises: 2c66cda35855
Create Date: 2017-03-16 13:22:16.678000

"""

# revision identifiers, used by Alembic.
revision = '398210bf0783'
down_revision = '2c66cda35855'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revises', sa.Column('flag', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revises', 'flag')
    ### end Alembic commands ###
