"""init migration

Revision ID: 3f3574c6edbc
Revises: 3cb3845f2390
Create Date: 2017-03-23 12:11:34.291000

"""

# revision identifiers, used by Alembic.
revision = '3f3574c6edbc'
down_revision = '3cb3845f2390'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savedatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrumentID', sa.String(length=32), nullable=True),
    sa.Column('datatype', sa.String(length=32), nullable=True),
    sa.Column('value', sa.String(length=32), nullable=True),
    sa.Column('separation', sa.String(length=32), nullable=True),
    sa.Column('VWRTHD', sa.String(length=32), nullable=True),
    sa.Column('stand', sa.String(length=32), nullable=True),
    sa.Column('up', sa.String(length=32), nullable=True),
    sa.Column('down', sa.String(length=32), nullable=True),
    sa.Column('fre', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrumentID'], ['instruments.instrumentID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savedatas')
    ### end Alembic commands ###
