"""init migration

Revision ID: 424f2b71dd4d
Revises: 3a04cbb17a37
Create Date: 2016-06-14 15:49:05.314000

"""

# revision identifiers, used by Alembic.
revision = '424f2b71dd4d'
down_revision = '3a04cbb17a37'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messuredatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrumentid', sa.Integer(), nullable=True),
    sa.Column('datatype', sa.String(length=32), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrumentid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messuredatas')
    ### end Alembic commands ###
