"""init migration

Revision ID: 50686f5a051a
Revises: 398210bf0783
Create Date: 2017-03-16 14:10:57.887000

"""

# revision identifiers, used by Alembic.
revision = '50686f5a051a'
down_revision = '398210bf0783'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messuredatas', sa.Column('fre', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messuredatas', 'fre')
    ### end Alembic commands ###
