"""init migration

Revision ID: 58555e370a5d
Revises: f94ac1e6c0b
Create Date: 2016-06-14 11:14:58.485000

"""

# revision identifiers, used by Alembic.
revision = '58555e370a5d'
down_revision = 'f94ac1e6c0b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    ### end Alembic commands ###
